version: "3"

services:
  graphql-server:
    container_name: graphql-server
    build:
      context: .
      target: graphql-server
    env_file: .env.example
    environment:
      DB_HOST: db
    ports:
      - "${GQL_PORT}:4350"
    mem_limit: 300m
    mem_reservation: 100m
    depends_on:
      - db

  squid-indexer:
    container_name: squid-indexer
    build:
      context: .
      target: squid-indexer
    env_file: .env.example
    environment:
      PROCESSOR_PROMETHEUS_PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    container_name: subsquid_db
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    shm_size: 1gb
    ports:
      - "${DB_PORT}:5432"
#    command: ["postgres", "-c", "log_statement=all"]
#    volumes:
#      - ./data/db:/var/lib/postgresql/data

