name: Cypress tests
on:
  pull_request:
    paths:
      - 'packages/ui/**/*'
      - '.github/workflows/cypress-tests.yaml'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        id: yarn-build-cache
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
            **/build
          key: ${{ runner.os }}-node_modules-files-build-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-
      - name: Install and show git version
        run: apt-get -y install git && git --version
        id: git-install
      - name: run docker-compose
        uses: sudo-bot/action-docker-compose@latest
        with:
          # https://docs.docker.com/compose/reference/overview/
          cli-args: |
            "up"
            "db"
            "-d"
      - name: Install indexer deps
        working-directory: squid
        run: npm ci
      - name: run indexer routine
        working-directory: squid
        run: |
          npm run codegen
          npm run typegen
          npm run build
          npm run db:migrate
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: packages/ui
          install-command: yarn install
          start: |
            npx --yes @acala-network/chopsticks@latest --config ../../chopsticks-config.yml
            cd packages/ui && yarn start
            cd squid && npm run start:graphql-server
            cd squid && node -r dotenv/config ../../squid/lib/main dotenv_config_path=assets/envs/.env.chopsticks
          wait-on: 'http://localhost:3333'
          # custom test command to run
          command: yarn test:ci
        env:
          VITE_CHAIN_ID: 'kusama'
          VITE_NETWORK_NAME: 'kusama'
          VITE_WS_PROVIDER: 'ws://localhost:8000'
          VITE_GRAPHQL_WS_PROVIDER: 'ws://localhost:4350/graphql'
          VITE_GRAPHQL_HTTP_PROVIDER: 'http://localhost:4350/graphql'
      # store the screenshots if the tests fail
      - name: Store screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: packages/ui/cypress/screenshots
      # store the videos if the tests fail
      - name: Store videos
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: packages/ui/cypress/videos
