name: Cypress tests
on:
  pull_request:
    paths:
      - 'packages/ui/**/*'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/ui
    container: cypress/browsers:node-20.5.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-build-cache
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
            **/build
          key: ${{ runner.os }}-node_modules-files-build-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-
      - name: Install and show git version
        run: apt-get -y install git && git --version
        id: git-install
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn start
          # wait for 10min for the server to be ready
          wait-on: 'npx wait-on --timeout 600000 http://localhost:3333'
          # custom test command to run
          command: yarn test:ci
      # store the screenshots if the tests fail
      - name: Store screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # store the videos if the tests fail
      # - name: Store videos
      #   uses: actions/upload-artifact@v1
      #   if: failure()
      #   with:
      #     name: cypress-videos
      #     path: cypress/videos
