# naming convention: <project>/<environment>/<task>
name: subsquid aquarium deployment

on:
  push:
    paths:
      - 'squid/**'
      - '.github/workflows/deploy-squid-stage.yaml'
    branches:
      - main
      - tbaut-use-aquarium # run this workflow if the branch starts with ci/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install @subsquid/cli
        run: npm install --location=global @subsquid/cli
      - name: auth subsquid
        run: |
          sqd auth -k ${{ secrets.SUBSQUID_DEPLOYMENT_KEY }}
      - name: deploy subsquid
        id: deploy
        run: sqd deploy -u .
