name: multix/stage/deploy

on:
  push:
    paths:
      - 'packages/squid/**'
      - '.github/workflows/deploy-squid-stage.yaml'
    branches:
      - main
      - ci/* # run this workflow if the branch starts with ci/*

env:
  # secrets are listed here to simplify the readability
  AWS_REGION: '${{ secrets.AWS_REGION }}'
  AWS_ACCOUNT_ID: '${{ secrets.AWS_ACCOUNT_ID }}'
  AWS_ROLE_NAME: '${{ secrets.AWS_ROLE_NAME }}'
  GHCR_TOKEN: '${{ secrets.GHCR_TOKEN }}'
  APP_STAGE: 'stage'
  DOCKER_REGISTRY: 'ghcr.io'
  DOCKER_TAG: 'latest'
  ENV_FILE: '${{ secrets.ENV_FILE }}'

jobs:
#  push:
#    name: push
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        target: [ 'squid-indexer', 'graphql-server' ]
#
#    permissions:
#      contents: read
#      id-token: write
#
#    steps:
#      - name: checkout the source code
#        uses: actions/checkout@v3
#
#      - name: setup docker buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: login to ghcr
#        uses: docker/login-action@v2
#        with:
#          registry: ${{ env.DOCKER_REGISTRY }}
#          username: ${{ github.repository_owner }}
#          password: ${{ env.GHCR_TOKEN }}
#
#      - name: docker build image
#        uses: docker/build-push-action@v4
#        env:
#          BUILDX_NO_DEFAULT_ATTESTATIONS: 1
#        with:
#          context: .
#          push: true
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#          provenance: false
#          target: ${{ matrix.target }}
#          platforms: |
#            linux/amd64
#          tags: |
#            ${{ env.DOCKER_REGISTRY }}/chainsafe/multix-${{ matrix.target }}:${{ env.DOCKER_TAG }}
#            ${{ env.DOCKER_REGISTRY }}/chainsafe/multix-${{ matrix.target }}:${{ github.sha }}

  deploy:
#    needs: push
    name: deploy
    runs-on: self-hosted
    strategy:
      matrix:
        network: [ 'rococo', 'kusama' ]

    permissions:
      contents: read
      id-token: write

    steps:
      - name: checkout the source code
        uses: actions/checkout@v3

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: install yarn
        run: npm install -g yarn

      - name: setup nodejs with yarn cache
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'

      - name: install dependencies in root and squid package
        run: |
          yarn install --frozen-lockfile
          yarn run squid:install

      - name: build the squid package
        run: yarn run squid:build

      - name: generate database credentials
        env:
          SECRET_NAME: '${{ env.APP_STAGE }}/multix/${{ matrix.network }}'
        run: generate-credentials "${{ env.SECRET_NAME }}" "${{ env.AWS_REGION }}"

#      - name: dump database
#        env:
#          DATABASE_NAME: 'multix-${{ env.APP_STAGE }}-${{ matrix.network }}'
#        run: psql

      - name: run migrations and start again
        run: |
          source "${{ env.ENV_FILE }}"
          npm run squid:migrate

#      - name: update cluster service
#        env:
#          AWS_CLUSTER_NAME: 'multix-${{ env.APP_STAGE }}'
#        run: aws ecs update-service --force-new-deployment --cluster ${{ env.AWS_CLUSTER_NAME }} --service ${{ matrix.network }} --region ${{ env.AWS_REGION }} > output.txt

#      - name: cleanup credentials
#        if: always()
#        run: cleanup-credentials
#
#      - name: uninstall yarn
#        if: always()
#        run: npm uninstall -g yarn