name: Lint squid
on:
  pull_request:
    paths: ["squid/**/*"]
jobs:
  extract:
    name: eslint
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./squid/
    steps:
    - uses: actions/checkout@v3

    - name: set user
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
    # use node module caching
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: install packages
      run: npm ci

    - name: lint
      run: npm run lint